# Generated by Django 4.1.6 on 2023-02-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
