# Generated by Django 3.2 on 2023-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_app', '0006_auto_20230301_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=200),
        ),
    ]
